version: "3.1"

services:
  db:
    image: mariadb:latest
    restart: always
    volumes:
      - ~/docker/maria:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
    environment:
      MYSQL_ROOT_PASSWORD: test
  redis:
    image: redis:latest
  crypto:
    build: .
    env_file: .env
    command: bash -c "bundle exec rackup -p 3000 -o '0.0.0.0'"
    volumes:
      - .:/var/www/crypto
    ports:
      - 9292:3000
    depends_on:
      - db
      - redis
  crypto-worker:
    build: .
    env_file: .env
    command: bash -c "ruby bin/trigger.rb"
    volumes:
      - .:/var/www/crypto
    depends_on:
      - db
      - redis