default: &default
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  coin_api: https://api.coingecko.com/api/v3/simple/price/
  redis_url: <%= ENV['REDIS_URL'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
